const USER_TYPES = {
  ADMIN: "1",
  VENDOR: "2",
};
const ORDER_STATUS = {
  IN_PROGRESS: 2,
  REJECTED: 3,
  COMPLETED: 4,
  OUT_FOR_DELIVERY: 5,
  DELIVERED: 6,
  REFUNDED: 7,
  CANCELLED: 8,
};
const ORDER_LINE_STATUS = {
  IN_PROGRESS: 2,
  REJECTED: 3,
  READY_FOR_DELIVERY: 5,
  OUT_FOR_DELIVERY: 5,
  DELIVERED: 6,
};
const PAYMENT_STATUS = {
  COD: 1,
  PAID: 2,
};
const FACTORY_STATUS = {
  ONLINE: 1,
  OFFLINE: 2,
};
module.exports = {
  USER_TYPES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  FACTORY_STATUS,
  ORDER_LINE_STATUS
};
